# Generated by Django 5.0.6 on 2024-05-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBpereval', '0002_rename_data_perevalimage_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='autumn',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='spring',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='summer',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='winter',
        ),
        migrations.AddField(
            model_name='level',
            name='autumn',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], default='1A', max_length=2),
        ),
        migrations.AddField(
            model_name='level',
            name='spring',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], default='1A', max_length=2),
        ),
        migrations.AddField(
            model_name='level',
            name='summer',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], default='1A', max_length=2),
        ),
        migrations.AddField(
            model_name='level',
            name='winter',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], default='1A', max_length=2),
        ),
    ]
