# Generated by Django 5.0.6 on 2024-05-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBpereval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevalimage',
            old_name='data',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='perevalimage',
            name='pereval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DBpereval.pereval'),
        ),
    ]
